# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 467c56b4e13a8cfd15ba61e978341636074f8fa278a949bc76e9a63ea6282bcf373df147e8973c0f4cd04b1feecb6894be3656f69e5f5d8d40b39caf2714ddd9

test:
  secret_key_base: fcf259012d5febec5d718445dddc5d774b389153ab51046235148a5c6951762dcfc398ab100f85f4220490104fabf22818d1d0d3885c1ba5725e8d324535305f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
